"""Metacognition service — Tuesday's self-awareness layer.

Observes patterns in Harman's thinking, builds connections between
knowledge files via wiki-links, and produces periodic insight reports
for Harman to audit.

Two frequencies:
1. Post-conversation pass (after 10+ message sessions) — lightweight
   Haiku call to extract patterns and update knowledge/patterns.md
2. Weekly synthesis (Monday 6am SGT) — deep Opus call producing
   an auditable Insight Report in knowledge/insights/
"""

from __future__ import annotations

import logging
import re
from datetime import datetime, timezone, timedelta
from pathlib import Path

from anthropic import AsyncAnthropic

from app.config import settings

logger = logging.getLogger("tuesday.metacognition")

SGT = timezone(timedelta(hours=8))

PATTERN_EXTRACTION_PROMPT = """You are Tuesday's metacognitive layer. You observe Harman's thinking patterns, values in action, decision-making tendencies, and emotional states across conversations.

Given the following conversation, extract structured observations. Be specific — quote actual phrases where possible. Only note genuine patterns, not surface-level observations.

Return your analysis in this EXACT markdown format (include only sections where you found something):

### Thinking Modalities
- [observation with [[wiki-link]] to relevant knowledge file]

### Decision Patterns
- [observation]

### Values in Action
- [observation linking to [[principles]] or [[disposition]]]

### Emotional Landscape
- [observation]

### New Facts Learned
- [fact that should be recorded]

### Connections Identified
- [[file1]] connects to [[file2]] because [reason]

### Shifts or Evolution
- [any change from previously known patterns]

Use these wiki-link targets: [[identity]], [[disposition]], [[expertise]], [[preferences]], [[principles]], [[context]], [[style]], [[decisions]]

If the conversation is trivial or contains no meaningful patterns, respond with just: "No significant patterns observed."

---

CONVERSATION:

{conversation}"""


WEEKLY_SYNTHESIS_PROMPT = """You are Tuesday's metacognitive layer performing a weekly synthesis. Review ALL of the following material and produce a comprehensive Insight Report.

Your job is to:
1. Identify emerging patterns in Harman's thinking across multiple conversations
2. Spot shifts or evolution from previously known patterns
3. Find recurring themes that connect across different domains (school, family, personal)
4. Flag contradictions or uncertainties that need Harman's review
5. Suggest knowledge file updates where understanding has deepened
6. Build connections between knowledge areas using [[wiki-links]]

Be honest, specific, and insightful. This report is for Harman to audit — he values depth, not flattery.

---

## Recent Patterns (from patterns.md):
{patterns}

## Recent Session Summaries:
{summaries}

## Current Knowledge Files:
{knowledge}

---

Produce the report in this format:

# Insight Report — {date}

## Period Covered
[dates]

## Emerging Patterns
[what you see forming across conversations]

## Shifts & Evolution
[how Harman's thinking/priorities have changed]

## Recurring Themes
[threads that keep appearing]

## Connections Discovered
[links between knowledge areas, using [[wiki-links]]]

## Contradictions & Uncertainties
*These require your review, Harman:*
- [things that seem inconsistent or need confirmation]

## Confidence Levels
- [HIGH] [things Tuesday is very sure about]
- [MEDIUM] [things that seem right but could be wrong]
- [LOW / NEEDS CONFIRMATION] [things to verify]

## Suggested Knowledge Updates
[specific changes to propose for knowledge files]

---
*Generated by Tuesday's metacognitive layer.*
*Review status: PENDING*"""


# --- Link Registry ---

_link_registry: dict[str, str] | None = None


def build_link_registry() -> dict[str, str]:
    """Build a map of linkable terms → target files from knowledge file headers."""
    global _link_registry
    registry: dict[str, str] = {}

    knowledge_dir = settings.knowledge_dir
    target_files = [
        "identity.md", "disposition.md", "expertise.md",
        "preferences.md", "principles.md", "context.md",
        "style.md", "decisions.md", "patterns.md",
    ]

    for filename in target_files:
        filepath = knowledge_dir / filename
        if not filepath.exists():
            continue

        stem = filepath.stem  # e.g., "identity"
        registry[stem] = stem  # Base name always linkable

        # Extract H2 and H3 headers as linkable terms
        content = filepath.read_text()
        for match in re.finditer(r"^#{2,3}\s+(.+)$", content, re.MULTILINE):
            header = match.group(1).strip()
            # Store as "term" → "file#section"
            registry[header.lower()] = f"{stem}#{header}"

    _link_registry = registry
    return registry


def inject_wiki_links(text: str) -> str:
    """Inject Obsidian-compatible [[wiki-links]] into text.

    Only links terms that aren't already inside [[ ]] brackets.
    Links first occurrence of each term per paragraph only.
    """
    registry = _link_registry or build_link_registry()

    # Don't re-link already-linked terms
    already_linked = set(re.findall(r"\[\[([^\]]+)\]\]", text))

    for term, target in sorted(registry.items(), key=lambda x: -len(x[0])):
        if term in already_linked or target in already_linked:
            continue
        if len(term) < 4:  # Skip very short terms to avoid false positives
            continue

        # Replace first occurrence only (case-insensitive, word boundary)
        pattern = re.compile(r"\b" + re.escape(term) + r"\b", re.IGNORECASE)
        if pattern.search(text):
            text = pattern.sub(f"[[{target}]]", text, count=1)
            already_linked.add(target)

    return text


# --- Pattern Extraction (Post-Conversation) ---

async def extract_patterns(messages: list[dict]) -> str | None:
    """Extract patterns from a conversation using Haiku (fast/cheap)."""
    # Build conversation text from messages
    conversation_lines = []
    for msg in messages:
        role = msg.get("role", "unknown")
        content = msg.get("content", "")
        if isinstance(content, list):
            content = " ".join(
                b.get("text", "") for b in content
                if isinstance(b, dict) and b.get("type") == "text"
            )
        if isinstance(content, str) and content.strip():
            conversation_lines.append(f"{role}: {content[:500]}")

    if len(conversation_lines) < 5:
        return None  # Too short to analyze

    conversation_text = "\n".join(conversation_lines[-30:])  # Last 30 messages max

    prompt = PATTERN_EXTRACTION_PROMPT.format(conversation=conversation_text)

    try:
        client = AsyncAnthropic(api_key=settings.anthropic_api_key)
        response = await client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=2048,
            messages=[{"role": "user", "content": prompt}],
        )
        result = response.content[0].text if response.content else None

        if result and "No significant patterns" in result:
            return None

        return result
    except Exception as e:
        logger.error(f"Pattern extraction failed: {e}")
        return None


async def update_patterns(extracted: str) -> None:
    """Append extracted patterns to knowledge/patterns.md with wiki-links."""
    patterns_file = settings.knowledge_dir / "patterns.md"

    # Inject wiki-links
    linked_text = inject_wiki_links(extracted)

    now = datetime.now(SGT)
    date_str = now.strftime("%Y-%m-%d")
    time_str = now.strftime("%H:%M")

    entry = f"\n\n## {date_str} ({time_str})\n\n{linked_text}"

    # Append to patterns.md
    if patterns_file.exists():
        current = patterns_file.read_text()
    else:
        current = "# Patterns\n\nMeta-observations about Harman's thinking, behaviour, and evolution.\n"

    patterns_file.write_text(current + entry)

    # Reload system prompt so Tuesday has the latest patterns
    from app.services.claude_service import reload_system_prompt
    reload_system_prompt()

    logger.info(f"Patterns updated: {len(linked_text)} chars added")


async def run_metacognitive_pass(session_id: str, messages: list[dict]) -> None:
    """Run the post-conversation metacognitive pass. Called as background task."""
    try:
        # Only run if conversation has enough substance
        user_messages = [m for m in messages if m.get("role") == "user"]
        if len(user_messages) < settings.metacognition_min_messages:
            return

        extracted = await extract_patterns(messages)
        if extracted:
            await update_patterns(extracted)
            logger.info(f"Metacognitive pass complete for session {session_id}")
    except Exception as e:
        logger.error(f"Metacognitive pass failed for session {session_id}: {e}")


# --- Weekly Synthesis ---

async def run_weekly_synthesis() -> str | None:
    """Run the weekly deep synthesis. Produces an Insight Report."""
    try:
        knowledge_dir = settings.knowledge_dir

        # Read patterns
        patterns_file = knowledge_dir / "patterns.md"
        patterns = patterns_file.read_text() if patterns_file.exists() else "No patterns recorded yet."

        # Read recent session summaries
        summaries = ""
        summaries_file = knowledge_dir / "session_summaries.md"
        if summaries_file.exists():
            summaries = summaries_file.read_text()

        # Also read monthly summaries
        summaries_dir = knowledge_dir / "summaries"
        if summaries_dir.exists():
            for sf in sorted(summaries_dir.glob("*.md"), reverse=True)[:4]:
                summaries += f"\n\n--- {sf.stem} ---\n" + sf.read_text()

        # Read core knowledge files
        from app.services.knowledge_loader import load_knowledge
        knowledge = load_knowledge()

        now = datetime.now(SGT)
        date_str = now.strftime("%Y-%m-%d")

        prompt = WEEKLY_SYNTHESIS_PROMPT.format(
            patterns=patterns[:20000],
            summaries=summaries[:15000],
            knowledge=knowledge[:30000],
            date=date_str,
        )

        client = AsyncAnthropic(api_key=settings.anthropic_api_key)
        response = await client.messages.create(
            model="claude-opus-4-6",
            max_tokens=8192,
            messages=[{"role": "user", "content": prompt}],
        )

        report = response.content[0].text if response.content else "Synthesis failed."

        # Inject wiki-links
        report = inject_wiki_links(report)

        # Save to insights directory
        insights_dir = knowledge_dir / "insights"
        insights_dir.mkdir(parents=True, exist_ok=True)
        report_path = insights_dir / f"{date_str}-weekly.md"
        report_path.write_text(report)

        logger.info(f"Weekly synthesis complete: {report_path}")
        return str(report_path)

    except Exception as e:
        logger.error(f"Weekly synthesis failed: {e}")
        return None
